[[topics]]
    topic = "Clock rate"
    chip = true
    title = "Clock rate"
    text = """
The ATtiny boots up with the 16/20 MHz oscillator (OSC20M) running at 20 MHz as the clock source and a prescaler division factor of 6 giving a frequency of at 3.333 MHz <ref>74</ref>.

The clock source can be configured by temporarily disabling I/O register Configuration Change Protection (CCP) by setting 0xD8 as the value of <reg>CPU.CCP</reg> register, followed by setting the desired value to <reg>CLKCTRL.MCLKCTRLA.CLKSEL</reg> register.

OSC20M frequency is defined by frequency select bits (FREQSEL, default 0x0 = 20 MHz) of the oscillator configurator fuse (FUSE.OSCCFG <ref>30</ref>).



Ex 1: Disable prescaler
```C
#include <avr/io.h>
CPU_CCP = CCP_IOREG_gc; // 0xD8
CLKCTRL_MCLKCTRLB = 0;
```

"""

[[topics]]
    topic = "POWER"
    title = "Powering the ATtiny"
    text = """
Lorem ipsum about voltages
"""

[[topics]]
    topic = "PORTA"
    title = "Port A IO pins"
    text = """
Port A IO pins are operated via the PORTA registry which follows the generic <reg>PORT</reg> layout
"""

[[topics]]
    topic = "PORTB"
    title = "Port B IO pins"
    text = """
Port B IO pins are operated via the PORTB registry which follows the generic <reg>PORT</reg> layout
"""

[[topics]]
    topic = "TWI"
    title = "Two-Wire Interface (I2C)"
    text = """
Lorem ipsum about the horrors of I2C
"""

[[topics]]
    topic = "TWI-ALT"
    title = "Two-Wire Interface (I2C) (Alternative pin configuration)"
    text = """
Alternative pin position for TWI outputs can be enabled via <reg>PORTMUX.CTRLB</reg>
"""

[[topics]]
    topic = "PWM"
    title = "Pulse Width Modulation"
    chip = true
    text = """
The best option for PWM is the <topic>TCA</topic> for 3 PWM outputs, or <topic>TCA-SPLIT</topic> for 6 PWM outputs.
"""

[[topics]]
    topic = "TCA"
    title = "16-bit Timer/Counter Type A"
    text = """
This timer/counter comes with three compare channels and is able to generate PWM waveforms. In normal 16-bit mode it can output to three pins and in 8-bit split mode it can drive up to 6 PWM pins.
"""


[[topics]]
    topic = "TCA-SPLIT"
    title = "16-bit Timer/Counter Type A (Split Mode)"
    text = """
Lorem ipsum about split mode
"""

[[topics]]
    topic = "TCA-ALT"
    title = "16-bit Timer/Counter Type A (Alternative pin configuration)"
    text = """
Alternative pin position for TCA0 waveform 0 (W0) output can be enabled via <reg>PORTMUX.CTRLC.TCA0</reg>
"""


[[topics]]
    topic = "TCB"
    title = "16-bit Timer/Counter Type B"
    text = """
Lorem ipsum about the joys of TCB
"""

[[topics]]
    topic = "TCD"
    title = "12-bit Timer/Counter Type D"
    text = """
Lorem ipsum about the joys of TCD
"""

[[topics]]
    topic = "ADC"
    title = "Analog to digital converter"
    text = """
Lorem ipsum about ADC
"""

[[topics]]
    topic = "SPI"
    title = "Serial Peripheral Interface (SPI)"
    text = """
Lorem ipsum about SPI
"""


[[topics]]
    topic = "SPI-ALT"
    title = "Serial Peripheral Interface (SPI) (Alternative pin configuration)"
    text = """
Lorem ipsum about ADC
"""


[[topics]]
    topic = "UPDI"
    title = "Unified Program and Debug Interface (UPDI)"
    text = """
Lorem ipsum about UPDI
"""


[[topics]]
    topic = "RESET"
    title = "Reset"
    text = """
Lorem ipsum about reset
"""

[[topics]]
    topic = "EVOUT"
    title = "Event system output"
    text = """
Lorem ipsum about event system
"""

[[topics]]
    topic = "TOSC"
    title = "External Crystal Oscillator"
    text = """
Lorem ipsum about TOSC
"""

[[topics]]
    topic = "EXTCLK"
    title = "External Clock Source"
    text = """
Lorem ipsum about EXTCLK
"""


[[topics]]
    topic = "Fuses"
    chip = true
    title = "Fuses"
    text = """
Lorem ipsum about fuses
"""

[[topics]]
    topic = "RTC"
    chip = true
    title = "16-bit Real Time Clock (RTC)"
    text = """
Lorem ipsum about RTC
"""


[[topics]]
    topic = "AC"
    title = "Analog converter"
    text = """
Lorem ipsum about AC
"""

[[topics]]
    topic = "DAC"
    title = "Digital to analog converter"
    text = """
Lorem ipsum about DAC
"""

[[topics]]
    topic = "USART"
    title = "Universal Serial A...?"
    text = """
Lorem ipsum about USART
"""

[[topics]]
    topic = "USART-ALT"
    title = "Universal Serial A...? (Alternative pin configuration)"
    text = """
Alternative pin configuration for the USART is available on all chips except ATTiny814. These can be enabled via <reg>PORTMUX.CTRLB.SPI0</reg>
"""

[[topics]]
    topic = "CCL"
    title = "Custom Chip Logic"
    text = """
Lorem ipsum about CCL
"""