[[topics]]
    topic = "Frequency"
    chip = true
    title = "Operating Frequency"
    text = """
The ATtiny boots up with the 16/20 MHz oscillator (OSC20M) running at 20 MHz as the clock source and a prescaler division factor of 6 giving a frequency of at 3.333 MHz <REF:74>.

The clock source can be configured by temporarily disabling I/O register Configuration Change Protection (CCP) by setting 0xD8 as the value of <REG:CPU.CCP> register, followed by setting the desired value to <REG:CLKCTRL.MCLKCTRLA.CLKSEL> register.

OSC20M frequency is defined by frequency select bits (FREQSEL, default 0x0 = 20 MHz) of the oscillator configurator fuse (FUSE.OSCCFG <REF:30>).
"""

[[topics]]
    topic = "POWER"
    title = "Powering the ATtiny"
    text = """
Lorem ipsum about voltages
"""

[[topics]]
    topic = "PORTA"
    title = "Port A IO pins"
    text = """
Port A IO pins are operated via the PORTA registry which follows the generic R:PORT layout
"""

[[topics]]
    topic = "PORTB"
    title = "Port B IO pins"
    text = """
Port B IO pins are operated via the PORTB registry which follows the generic R:PORT layout
"""

[[topics]]
    topic = "TWI"
    title = "Two-Wire Interface (I2C)"
    text = """
Lorem ipsum about the horrors of I2C
"""

[[topics]]
    topic = "TWI-ALT"
    title = "Two-Wire Interface (I2C) (Alternative pin configuration)"
    text = """
Alternative pin position for TWI outputs can be enabled via R:PORTMUX.CTRLB
"""

[[topics]]
    topic = "TCA"
    title = "16-bit Timer/Counter Type A"
    text = """
Lorem ipsum about the joys of TCA
"""

[[topics]]
    topic = "TCA-SPLIT"
    title = "16-bit Timer/Counter Type A (Split Mode)"
    text = """
Lorem ipsum about split mode
"""

[[topics]]
    topic = "TCA-ALT"
    title = "16-bit Timer/Counter Type A (Alternative pin configuration)"
    text = """
Alternative pin position for TCA0 waveform 0 (W0) output can be enabled via R:PORTMUX.CTRLC.TCA0
"""

[[topics]]
    topic = "ADC"
    title = "Analog to digital converter"
    text = """
Lorem ipsum about ADC
"""


[[topics]]
    topic = "UPDI"
    title = "Unified Program and Debug Interface (UPDI)"
    text = """
Lorem ipsum about UPDI
"""


[[topics]]
    topic = "RESET"
    title = "Reset"
    text = """
Lorem ipsum about reset
"""

[[topics]]
    topic = "Fuses"
    chip = true
    title = "Fuses"
    text = """
Lorem ipsum about fuses
"""

[[topics]]
    topic = "RTC"
    chip = true
    title = "Real Time Clock (RTC)"
    text = """
Lorem ipsum about RTC
"""

