[[regs]]
    name = "PORTMUX"
    datasheetPage = 125
    [[regs.offsets]]
        name = "CTRLA"
        [[regs.offsets.fields]]
            name = "EVOUT0"
            description = "Event output 0"
        [[regs.offsets.fields]]
            name = "EVOUT1"
            description = "Event output 1"
        [[regs.offsets.fields]]
            size = 6
    [[regs.offsets]]
        name = "CTRLB"
        [[regs.offsets.fields]]
            name = "USART0"
            description = "Enable to select alternative USART pin configuration"
            relatedGroups = ["USART-ALT"]
        [[regs.offsets.fields]]
        [[regs.offsets.fields]]
            name = "SPI0"
            description = "Enable to select alternative SPI pin configuration"
            relatedGroups = ["SPI-ALT"]
        [[regs.offsets.fields]]
        [[regs.offsets.fields]]
            name = "TWI0"
            description = "Enable to select alternative TWI pin configuration"
            relatedGroups = ["TWI-ALT"]
        [[regs.offsets.fields]]
            size = 3

    [[regs.offsets]]
        name = "CTRLC"
        [[regs.offsets.fields]]
            name = "TCA0"
            description = "Enable to select alternative TCA pin configuration"
            relatedGroups = ["TCA-ALT"]
        [[regs.offsets.fields]]
            size = 7
