default = """
The ATtiny boots up with the 16/20 MHz oscillator (OSC20M) and a prescaler
division factor of 6 <sup>\[[datasheet](datasheet.pdf?page=74)\]</sup>.
OSC20M frequency is set by frequency select bits (FREQSEL, default 0x0 = 20 MHz) of
the oscillator configurator fuse (FUSE.OSCCFG). Shortly put, the ATtiny boots up by
default running at 3.33 MHz. To get it to run at 20 MHz, the prescaler needs to be disabled
via register [CLKCTRL](datasheet.pdf?page=78). And to do that, the configuration
change protection must be disabled via [CPU register](datasheet.pdf?page=52).
"""