[[pins]]
    pin = 1
        [[pins.attributes]]
            type = "vcc"
            label = "VCC"
            groups = ["POWER"]

[[pins]]
    pin = 2
        [[pins.attributes]]
            type = "port"
            label = "PA4"
            groups = ["PORTA"]
        [[pins.attributes]]
            type = "adc"
            label = "AIN4"
            groups = ["ADC"]
        [[pins.attributes]]
            type = "spi"
            label = "SS"
            groups = ["SPI"]
        [[pins.attributes]]
            type = "tca"
            label = "WO4"
            groups = ["TCA-SPLIT"]
        [[pins.attributes]]
            type = "tcd"
            label = "WOA"
            groups = ["TCD"]

[[pins]]
    pin = 3
        [[pins.attributes]]
            type = "port"
            label = "PA5"
            groups = ["PORTA"]
        [[pins.attributes]]
            type = "adc"
            label = "AIN5"
            groups = ["ADC"]
        [[pins.attributes]]
            type = "tca"
            label = "WO5"
            groups = ["TCA-SPLIT"]
        [[pins.attributes]]
            type = "tcb"
            label = "WO"
            groups = ["TCB"]
        [[pins.attributes]]
            type = "tcd"
            label = "WOB"
            groups = ["TCD"]


[[pins]]
    pin = 4
        [[pins.attributes]]
            type = "port"
            label = "PA6"
            groups = ["PORTA"]
        [[pins.attributes]]
            type = "adc"
            label = "AIN6"
            groups = ["ADC"]
        [[pins.attributes]]
            type = "spi"
            alt = true
            label = "MOSI"
            groups = ["SPI-ALT", "SPI"]


[[pins]]
    pin = 5
        [[pins.attributes]]
            type = "port"
            label = "PA7"
            groups = ["PORTA"]
        [[pins.attributes]]
            type = "adc"
            label = "AIN7"
            groups = ["ADC"]
        [[pins.attributes]]
            type = "spi"
            alt = true
            label = "MISO"
            groups = ["SPI-ALT", "SPI"]

[[pins]]
    pin = 6
        [[pins.attributes]]
            type = "port"
            label = "PB3"
            groups = ["PORTB"]
        [[pins.attributes]]
            type = "tca"
            alt = true
            label = "WO0"
            groups = ["TCA-ALT", "TCA", "TCA-SPLIT"]
        [[pins.attributes]]
            type = "clk"
            label = "TOSC1"
            groups = ["TOSC", "EXTCLK"]

[[pins]]
    pin = 7
        [[pins.attributes]]
            type = "port"
            label = "PB2"
            groups = ["PORTB"]
        [[pins.attributes]]
            type = "tca"
            label = "WO2"
            groups = ["TCA", "TCA-SPLIT"]
        [[pins.attributes]]
            type = "clk"
            label = "TOSC2"
            groups = ["TOSC", "EXTCLK"]
        [[pins.attributes]]
            type = "evout"
            label = "EVOUT1"
            groups = ["EVOUT"]

[[pins]]
    pin = 14
        [[pins.attributes]]
            type = "gnd"
            label = "GND"
            groups = ["POWER"]

[[pins]]
    pin = 13
        [[pins.attributes]]
            type = "port"
            label = "PA3"
            groups = ["PORTA"]
        [[pins.attributes]]
            type = "adc"
            label = "AIN3"
            groups = ["ADC"]
        [[pins.attributes]]
            type = "spi"
            label = "SCK"
            groups = ["SPI"]
        [[pins.attributes]]
            type = "tca"
            label = "WO3"
            groups = ["TCA-SPLIT"]

[[pins]]
    pin = 12
        [[pins.attributes]]
            type = "port"
            label = "PA2"
            groups = ["PORTA"]
        [[pins.attributes]]
            type = "adc"
            label = "AIN2"
            groups = ["ADC"]
        [[pins.attributes]]
            type = "spi"
            label = "MISO"
            groups = ["SPI"]
        [[pins.attributes]]
            type = "twi"
            alt = true
            label = "SCL"
            groups = ["TWI-ALT", "TWI"]
        [[pins.attributes]]
            type = "evout"
            label = "EVOUT0"
            groups = ["EVOUT"]
        [[pins.attributes]]
            type = "clk"
            label = "EXTCLK"
            groups = ["EXTCLK", "TOSC"]


[[pins]]
    pin = 11
        [[pins.attributes]]
            type = "port"
            label = "PA1"
            groups = ["PORTA"]
        [[pins.attributes]]
            type = "adc"
            label = "AIN1"
            groups = ["ADC"]
        [[pins.attributes]]
            type = "spi"
            label = "MOSI"
            groups = ["SPI"]
        [[pins.attributes]]
            type = "twi"
            alt = true
            label = "SDA"
            groups = ["TWI-ALT", "TWI"]


[[pins]]
    pin = 10
        [[pins.attributes]]
            type = "port"
            label = "PA0"
            alt = true
            groups = ["PORTA"]
        [[pins.attributes]]
            type = "adc"
            label = "AIN0"
            alt = true
            groups = ["ADC"]
        [[pins.attributes]]
            type = "updi"
            label = "UPDI"
            groups = ["UPDI", "RESET"]
        [[pins.attributes]]
            type = "reset"
            label = "RESET"
            groups = ["RESET", "UPDI"]
[[pins]]
    pin = 9
        [[pins.attributes]]
            type = "port"
            label = "PB0"
            groups = ["PORTB"]
        [[pins.attributes]]
            type = "adc"
            label = "AIN11"
            groups = ["ADC"]
        [[pins.attributes]]
            type = "twi"
            label = "SCL"
            groups = ["TWI"]
        [[pins.attributes]]
            type = "tca"
            label = "WO0"
            groups = ["TCA", "TCA-SPLIT"]



[[pins]]
    pin = 8
        [[pins.attributes]]
            type = "port"
            label = "PB1"
            groups = ["PORTB"]
        [[pins.attributes]]
            type = "adc"
            label = "AIN10"
            groups = ["ADC"]
        [[pins.attributes]]
            type = "twi"
            label = "SDA"
            groups = ["TWI"]
        [[pins.attributes]]
            type = "tca"
            label = "WO1"
            groups = ["TCA", "TCA-SPLIT"]